This is a testharness.js-based test.
[FAIL] navigator.credentials.create() rejects when aborted after the promise creation
  promise_rejects_exactly: function "function() { throw e; }" threw object "NotSupportedError: Only exactly one of 'password', 'federated', and 'publicKey' credential types are currently supported." but we expected it to throw object "Error: custom error"
Harness: the test ran to completion.

